import './App.css';

const Books = ({ books }) => {
  const filteredBooks = books.filter(
    (book) => book.genre === 'Science Fiction'
  );
  // console.log(filteredBooks)

  const booksListing = filteredBooks.map((book) => (
    <div key={book.id}>
      <h3>Title: {book.title}</h3>
      <p>Genre: {book.genre}</p>
    </div>
  ));

  return (
    <>
      <h2>Science Fiction Books</h2>
      {booksListing}
    </>
  );
};

const Users = ({ users }) => {
  const filteredUsers = users.filter((user) => user.role === 'Admin');

  const adminUsers = filteredUsers.map((user) => (
    <div key={user.id}>
      <h3>Name: {user.name}</h3>
      <p>Role: {user.role}</p>
    </div>
  ));

  return (
    <>
      <h2>Users of Admin Role</h2>
      {adminUsers}
    </>
  );
};

const Products = ({ products }) => {
  const filteredProducts = products.filter((product) => product.price > 100);

  const productsListing = filteredProducts.map((product) => (
    <div key={product.id}>
      <h3>Name: {product.name}</h3>
      <p>Price: ${product.price}</p>
      <p>Color: {product.features.color}</p>
      <p>Is it Waterproof ? {product.features.isWaterProof ? 'Yes' : 'No'}</p>
    </div>
  ));

  return (
    <>
      <h2>Products with price above $100</h2>
      {productsListing}
    </>
  );
};

const Cities = ({ cities }) => {
  const filteredCities = cities.filter((city) => city.population > 1000000);

  const citiesListing = filteredCities.map((city) => (
    <div key={city.id}>
      <h3>Name: {city.name}</h3>
      <p>Population: {city.population}</p>
    </div>
  ));

  return (
    <>
      <h2>Cities with population over 10 lakh</h2>
      {citiesListing}
    </>
  );
};

const Movies = ({ movies }) => {
  const filteredMovies = movies.filter((movie) => movie.releaseYear > 2015);

  const moviesListing = filteredMovies.map((movie) => (
    <div key={movie.id}>
      <h3>Title: {movie.title}</h3>
      <p>Release Year: {movie.releaseYear}</p>
    </div>
  ));

  return (
    <>
      <h2>Movies released after 2015</h2>
      {moviesListing}
    </>
  );
};

const Podcasts = ({ podcasts }) => {
  const filteredPodcasts = podcasts.filter(
    (podcast) => podcast.featured === true
  );
  // console.log(filteredPodcasts)

  const podcastsListing = filteredPodcasts.map((podcast) => (
    <div>
      <h3>Title: {podcast.title}</h3>
      <p>Host: {podcast.host.join(', ')}</p>
      <p>Featured: {podcast.featured ? 'Yes' : 'No'}</p>
    </div>
  ));

  return (
    <>
      <h2>Featured Podcasts</h2>
      {podcastsListing}
    </>
  );
};

const MoviesData = ({ moviesData }) => {
  const filteredMovies = moviesData.filter((movie) => movie.releaseYear > 2000);

  const totalDuration = filteredMovies.reduce(
    (acc, curr) => acc + curr.duration,
    0
  );

  const avgDuration = totalDuration / filteredMovies.length;

  return (
    <>
      <h2>Average Duration of Movies Released in 2000 and Above</h2>
      <p>{avgDuration}</p>
    </>
  );
};

const Tasks = ({ tasks }) => {
  const filteredTasks = tasks.filter((task) => task.completed === true);
  // console.log(filteredTasks)

  return (
    <>
      <h2>Total Number of Tasks Completed</h2>
      {filteredTasks.length}
    </>
  );
};

const Vehicles = ({ vehicles }) => {
  const totalDistance = vehicles.reduce((acc, curr) => acc + curr.distance, 0);

  return (
    <>
      <h2>Total Distance Traveled by Vehicles</h2>
      {totalDistance}
    </>
  );
};

const Sales = ({ sales }) => {
  const totalRevenue = sales.reduce(
    (acc, curr) => acc + curr.quantity * curr.price,
    0
  );
  // console.log(totalRevenue)

  return (
    <>
      <h2>Total Revenue Generated by all Sales Transations</h2>
      <p>{totalRevenue}</p>
    </>
  );
};

export default function App() {
  const books = [
    { id: 1, title: 'Dune', genre: 'Science Fiction' },
    { id: 2, title: 'Neuromancer', genre: 'Science Fiction' },
    { id: 3, title: 'Foundation', genre: 'Sci-fi' },
  ];

  const users = [
    { id: 1, name: 'Alice', role: 'User' },
    { id: 2, name: 'Bob', role: 'Admin' },
    { id: 3, name: 'Charlie', role: 'User' },
    { id: 4, name: 'John', role: 'Admin' },
  ];

  const products = [
    {
      id: 1,
      name: 'Laptop',
      price: 1200,
      features: { color: 'green', isWaterProof: false },
    },
    {
      id: 2,
      name: 'Smartphone',
      price: 800,
      features: { color: 'blue', isWaterProof: true },
    },
    {
      id: 3,
      name: 'Headphones',
      price: 150,
      features: { color: 'silver', isWaterProof: false },
    },
  ];

  const cities = [
    { id: 1, name: 'New York', population: 8500000 },
    { id: 2, name: 'Los Angeles', population: 539900 },
    { id: 3, name: 'Chicago', population: 2700000 },
  ];

  const movies = [
    { id: 1, title: 'Inception', releaseYear: 2010 },
    { id: 2, title: 'La La Land', releaseYear: 2016 },
    { id: 3, title: 'Interstellar', releaseYear: 2014 },
    { id: 4, title: 'Dune 2', releaseYear: 2024 },
  ];

  const podcasts = [
    { id: 1, title: 'Tech Talk', host: ['host 1'], featured: true },
    { id: 2, title: 'Business Insights', host: ['host 2'], featured: false },
    {
      id: 3,
      title: 'Science Hour',
      host: ['host 3', 'host 4'],
      featured: true,
    },
  ];

  const moviesData = [
    { id: 1, title: 'The Matrix', duration: 136, releaseYear: 1999 },
    { id: 2, title: 'Inception', duration: 148, releaseYear: 2010 },
    { id: 3, title: 'Avatar', duration: 162, releaseYear: 2009 },
  ];

  const tasks = [
    { id: 1, description: 'Complete project proposal', completed: true },
    { id: 2, description: 'Review client feedback', completed: false },
    { id: 3, description: 'Submit final report', completed: true },
  ];

  const vehicles = [
    { id: 1, name: 'Car', distance: 150 },
    { id: 2, name: 'Bicycle', distance: 10 },
    { id: 3, name: 'Motorcycle', distance: 75 },
  ];

  const sales = [
    { id: 1, product: 'Widget A', price: 25, quantity: 10 },
    { id: 2, product: 'Gadget B', price: 50, quantity: 5 },
    { id: 3, product: 'Tool C', price: 30, quantity: 8 },
  ];

  return (
    <main>
      <Books books={books} />
      <hr />
      <Users users={users} />
      <hr />
      <Products products={products} />
      <hr />
      <Cities cities={cities} />
      <hr />
      <Movies movies={movies} />
      <hr />
      <Podcasts podcasts={podcasts} />
      <hr />
      <MoviesData moviesData={moviesData} />
      <hr />
      <Tasks tasks={tasks} />
      <hr />
      <Vehicles vehicles={vehicles} />
      <hr />
      <Sales sales={sales} />
    </main>
  );
}
